# NOTE: Do not edit this file directly! It was generated
# automatically from the template file 'parkipy/_pk_kernels/templates/_celllist_template.py'
# by running ``preprocess.py``.
"""
PyKokkos kernels for the parkipy.CellList class
"""

from typing import List
import pykokkos as pk


@pk.workunit
def get_nonempty_neighbors(
    cell: int,
    grid_area,
    cell_grid_shape_0,
    cell_grid_shape_1,
    cell_grid_shape_2,
    nonempty_cell_index,
    nonempty_neighbors,
):
    cell_x: int = cell // grid_area
    cell_y: int = (cell % grid_area) // cell_grid_shape_2
    cell_z: int = (cell % grid_area) % cell_grid_shape_2
    for dx in range(-1, 2):
        neighbor_x: int = cell_x + dx
        if neighbor_x < 0 or neighbor_x >= cell_grid_shape_0:
            continue
        for dy in range(-1, 2):
            neighbor_y: int = cell_y + dy
            if neighbor_y < 0 or neighbor_y >= cell_grid_shape_1:
                continue
            for dz in range(-1, 2):
                neighbor_z: int = cell_z + dz
                if neighbor_z < 0 or neighbor_z >= cell_grid_shape_2:
                    continue
                neighbor_empty: int = (
                    neighbor_x * grid_area + neighbor_y * cell_grid_shape_2 + neighbor_z
                )

                neighbor: int = nonempty_cell_index[neighbor_empty]
                nonempty_neighbors[cell][dx + 1][dy + 1][dz + 1] = neighbor










@pk.workunit
def count_particles_fp32(i: int, counter, p, rc, box):
    cell: int = _get_cell_fp32(p, i, rc, box[0], box[1], box[2])
    pk.atomic_add(counter, [cell], 1)



@pk.function
def _get_cell_fp32(
    p: pk.View2D[pk.float],
    i: int,
    rc: pk.float,
    box_length_x: pk.float,
    box_length_y: pk.float,
    box_length_z: pk.float,
) -> int:
    num_cells: List[int] = [
        int(box_length_x / rc),
        int(box_length_y / rc),
        int(box_length_z / rc),
    ]

    cell_xyz: List[int] = [
        int(p[0][i] / (box_length_x / num_cells[0])),
        int(p[1][i] / (box_length_y / num_cells[1])),
        int(p[2][i] / (box_length_z / num_cells[2])),
    ]
    cell: int = (
        cell_xyz[0] * num_cells[2] * num_cells[1]
        + cell_xyz[1] * num_cells[2]
        + cell_xyz[2]
    )
    return cell



@pk.workunit
def reshuffle_particles_fp32(
    i: int,
    p_list,
    counter,
    l2g,
    p,
    cell2nz,
    rc,
    box,
    cell_size,
    dp,
):
    cell: int = _get_cell_fp32(p, i, rc, box[0], box[1], box[2])  # read
    cell_off: int = pk.atomic_fetch_add(counter, [cell], 1)  # write
    nz: int = cell2nz[cell]  # read
    l_idx: int = nz * cell_size + cell_off
    l2g[l_idx] = i  # write
    for k in range(dp):
        p_list[k][l_idx] = p[k][i]  # read + write



@pk.workunit
def reshuffle_forces_fp32(
    i: int,
    q_list,
    l2g,
    q,
    dq,
):
    glb: int = l2g[i]
    if glb < 0:
        return
    for k in range(dq):
        q_list[k][i] = q[k][glb]


@pk.workunit
def count_particles_fp64(i: int, counter, p, rc, box):
    cell: int = _get_cell_fp64(p, i, rc, box[0], box[1], box[2])
    pk.atomic_add(counter, [cell], 1)


@pk.function
def _get_cell_fp64(
    p: pk.View2D[pk.double],
    i: int,
    rc: pk.double,
    box_length_x: pk.double,
    box_length_y: pk.double,
    box_length_z: pk.double,
) -> int:
    num_cells: List[int] = [
        int(box_length_x / rc),
        int(box_length_y / rc),
        int(box_length_z / rc),
    ]

    cell_xyz: List[int] = [
        int(p[0][i] / (box_length_x / num_cells[0])),
        int(p[1][i] / (box_length_y / num_cells[1])),
        int(p[2][i] / (box_length_z / num_cells[2])),
    ]
    cell: int = (
        cell_xyz[0] * num_cells[2] * num_cells[1]
        + cell_xyz[1] * num_cells[2]
        + cell_xyz[2]
    )
    return cell


@pk.workunit
def reshuffle_particles_fp64(
    i: int,
    p_list,
    counter,
    l2g,
    p,
    cell2nz,
    rc,
    box,
    cell_size,
    dp,
):
    cell: int = _get_cell_fp64(p, i, rc, box[0], box[1], box[2])  # read
    cell_off: int = pk.atomic_fetch_add(counter, [cell], 1)  # write
    nz: int = cell2nz[cell]  # read
    l_idx: int = nz * cell_size + cell_off
    l2g[l_idx] = i  # write
    for k in range(dp):
        p_list[k][l_idx] = p[k][i]  # read + write


@pk.workunit
def reshuffle_forces_fp64(
    i: int,
    q_list,
    l2g,
    q,
    dq,
):
    glb: int = l2g[i]
    if glb < 0:
        return
    for k in range(dq):
        q_list[k][i] = q[k][glb]


