import os
import argparse
import numpy as np
import pandas as pd
import pickle


def main(args):
    """
    Main function. Takes `args` from the ArgumentParser at the bottom of this
    file.
    """
    ranks = [int(2**n) for n in range(int(np.log2(args.max_gpus)) + 1)]
    stages = [
        "p2p",
        "p2g",
        "fft",
        "cnv",
        "ifft",
        "g2p",
        "mpi_sort",
        "mpi_ghost",
        "mpi_grid_ghost",
    ]
    nindx = -1

    if args.format.upper() == "LATEX":
        string = "\\toprule\n"
        # list the distributions
        string += "& "
        for i, N in enumerate(ranks):
            string += f"{N}" + " &"
            if i < len(ranks) - 1:
                string += " "
        string = string[:-2]
        string += "\\\\\n"
        # list the times per stage
        for stage in stages:
            string += f"{stage} &"
            for N in ranks:
                data = load_times_from_disk(args, N)
                n = data["nt"][nindx]
                if stage == "total":
                    time = 0
                    for _stage in stages:
                        if _stage == "total":
                            continue
                        time += data["times"][_stage][:, nindx][1:].mean()
                        string += f"{round(time*1e3, 2)}" + " &"
                else:
                    if stage in stages[-3:] and N == 1:
                        time == "---"
                        string += f"---" + " &"
                    else:
                        time = data["times"][stage][:, nindx][1:].mean()
                        string += f"{round(time*1e3, 1)}" + " &"
                if i < len(ranks) - 1:
                    string += " "
            string = string[:-2]
            string += "\\\\\n"
        string += "\\bottomrule"
        print(string)
    elif args.format.upper() == "CL":
        raise NotImplementedError("CL format not yet implemented.")
        print(string)


def load_times_from_disk(args, N, timestamp="latest", version=1):
    fname = (
        f"distributed_ewald_timing_result_N{N}_up{args.up}_clsz{args.cell_size}_tol{args.tolerance}"
        f"_dev{args.device.upper()}_arch{args.arch}_v{version}_latest.pkl"
    )
    # print(f"Loading from {fname}")
    fpath = os.path.join(args.output_dir, fname)
    try:
        with open(fpath, "rb") as f:
            data_dict = pickle.load(f)
    except FileNotFoundError as e:
        msg = f"searching for {N}-GPU results; not found at path='{fpath}'; please run 'analysis/distributed/time_ewald.py' on {N} nodes to generate file"
        raise FileNotFoundError(msg) from e
    return data_dict


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Analyize Ewald sum timing across in a multi-gpu setting."
        "Results are generated by the 'analysis/distributed/time_ewald.py file.'"
    )
    parser.add_argument(
        "--up",
        dest="up",
        type=int,
        default=1,
        help="Set the upsampeling parameter (default: 16)",
    )
    parser.add_argument(
        "--device",
        dest="device",
        required=True,
        choices=("cuda", "hip", "host"),
        type=str,
        help="Device to run code on",
    )
    parser.add_argument(
        "--arch",
        dest="arch",
        choices=("80", "90", "94", None),
        type=str,
        help="Device compute architecture. `None` corresponds to the NVIDIA grace CPU, `80` the NVIDIA A100 GPU, `94` the NVIDIA GH200 GPU, and `94` the AMD MI300x GPU.",
    )
    parser.add_argument(
        "-t",
        "--timestamp",
        default="latest",
        help="timestamp of result file to load (default: latest)",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default="analysis/distributed/data",
        help="output directory for timing results (default: .)",
    )
    parser.add_argument(
        "--format", default="latex", help="output format, either 'latex' or 'cl'"
    )
    parser.add_argument(
        "--cell_size",
        type=int,
        default=224,
        help="Set the max src per cell (default: 160)",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=1e-4,
        help="Spectral Ewald tolerance",
    )
    parser.add_argument(
        "--max-gpus",
        type=int,
        default=64,
        help="Analyze timing results for 2^n GPUs up to '--max-gpus'."
        " E.g., for the default 64 GPUs, analyze results for [1,2,4,8,16,32,64] GPUs",
    )
    args = parser.parse_args()
    if args.device.upper() in ["CUDA", "HIP"] and args.arch is None:
        raise ValueError(
            "arch must be passed for GPU devices, see `--help` for details"
        )
    main(args)
    exit()
