#!python3

import argparse
import numpy as np
from scipy.special import i0 as I0

"""
Generate functions that evaluate polynomial approximations of the
Kaiser–Bessel window for given window support ``P`` and
polynomial degree ``deg``. The polynomial degree is determined
from ``P`` according to the rule ::

    deg = P/2 + 1,              if 2 <= P <= 10
        = min(P/2 + 2, 9),      if P >= 12

with ``P`` assumed to be even. This is based on experiments in
[Shamshirgar, Bagge, Tornberg, J. Chem. Phys., 2021].

The output is written to the standard output stream and can be
copied by hand into the file ``_pk_fs_workunits.py``.
"""


def main(args):
    print(
        "# NOTE: These functions are generated by ``generate_basic_kaiser_poly_functions.py``."
    )
    print("# They should not be modified by hand.")
    for P in range(2, args.max_P + 2, 2):
        generate_output(P)
    return 0


def generate_output(P):
    # Compute coefficients
    degree = determine_degree(P)
    coeffs = compute_polynomial_coefficients(P, degree)

    # Output function header and beginning
    print(
        f'''\

@pk.function
def _basic_kaiser_poly_p{P}(x: pk.double, i: int) -> float:
    """
    Evaluate the basic kaiser polynomial of support {P} and degree {degree}.

    Parameters
    ----------
    x : pk.double,
        the point to be evaluated
    i : int
        the fourier grid positioning of the
        point where the 0 index is the
        front/top/left and the 9 index
        is the back/bottom/right corner
        of a p-cube

    Returns
    -------
    pk.double
        output of the basic kaiser polynomial
    """
    z: pk.double = 2.0 * x - 1.0
''',
        end="",
    )
    for j in range(degree + 1):
        print(f"    c{j}: pk.double = 0.0")
    print()

    # Output coefficients
    for i in range(P):
        if i == 0:
            print(f"    if i == {i}:")
        elif i == P - 1:
            print(f"    else:  # i == {i}")
        else:
            print(f"    elif i == {i}:")
        for j in range(degree + 1):
            print(8 * " " + (f"c{j} = %.16e" % coeffs[j, i]))
    print()

    # Output Horner evaluation formula
    s = "c0"
    for j in range(1, degree):
        s += f" + z * (c{j}"
    s += f" + z * c{degree}"
    s += ")" * (degree - 1)
    print(f"    return {s}")
    return


def determine_degree(P):
    if P < 2:
        raise ValueError("P cannot be smaller than 2")
    elif P % 2 != 0:
        raise ValueError("P must be even")
    elif P <= 10:
        return P // 2 + 1
    else:
        return min(P // 2 + 2, 9)


def compute_polynomial_coefficients(P, degree):
    z = get_sample_points(degree)  # compute Chebyshev points
    V = get_interpolation_matrix(degree, z)  # compute Vandermonde matrix
    beta = 2.5 * P  # relation between beta and P
    Kfun = lambda x: I0(beta * np.sqrt(1 - x**2)) / I0(beta)
    h = 2 / P
    zsc = 0.5 * h * z
    i = np.arange(1, P + 1)
    bin_centers = np.flip(h * (i - 0.5) - 1)  # flip for consistency with SE

    Kz = np.zeros([np.size(z), P])
    for j in range(P):
        Kz[:, j] = Kfun(zsc + bin_centers[j])
    coeffs = np.linalg.solve(V, Kz)
    return coeffs


def get_sample_points(degree):
    n = degree + 1
    i = np.arange(1, n + 1)
    return np.cos(np.pi * (i - 0.5) / n)  # roots of Chebyshev polynomial T_n


def get_interpolation_matrix(degree, x):
    n = degree + 1
    V = np.ones([np.size(x), n])
    for j in range(1, n):
        V[:, j] = V[:, j - 1] * x
    return V


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate ``_basic_kaiser_poly`` functions for ``_pk_fs_workunits.py``."
    )
    parser.add_argument(
        "-P",
        dest="max_P",
        type=int,
        default=14,
        help="Maximum P value to generate output for",
    )
    args = parser.parse_args()
    exit(main(args))
