#!python3

import os
import argparse

"""
Preprocess template files. Running this script preprocesses all
templates files in the ``templates`` dict.

The template language
=====================

The template preprocessor is very simple. Its directives are
stored as Python comments. A template is introduced by the line
::

    # START TEMPLATE <NAME>

where ``<NAME>`` is replaced by the name of the template. It is
terminated by the line
::

    # END TEMPLATE <NAME>

(the name of the template is optional when ending a template; it
can be omitted).

The template consists of all lines between the start and end
lines. If the template name (``<NAME>``) appears anywhere in the
template, it will later be replaced -- so the name should be
chosen to be unique and not appear anywhere else (it is
case-sensitive).

The template is invoked using "applications". An application
start with the line
::

    # START APPLICATION <NAME> <APP>

where ``<NAME>`` is the name of the *template* to apply, and
``<APP>`` is the name of the application. The application ends
with
::

    # END APPLICATION <NAME> <APP>

(both ``<NAME>`` and ``<APP>`` can be omitted in the ending
line). The preprocessor will take any lines between the start and
end of the application, and then append the template itself, with
any instance of the template name ``<NAME>`` replaced by ``<APP>``
(case-sensitive).

Any lines that are outside template and application definitions
will simply be copied verbatim into the output. The only
exception is that lines starting with ``# TEMPLATE NOTE`` will be
omitted, and a comment will be added at the beginning of the
output, saying that the file was generated from a template.
"""

templates = {
    "templates/_p2p_workload.py": "_p2p_workload.py",
    "templates/_p2g_workload.py": "_p2g_workload.py",
    "templates/_g2p_workload.py": "_g2p_workload.py",
    "templates/_cnv_workunits.py": "_cnv_workunits.py",
}


def main(args):
    for template, output in templates.items():
        template = args.path + template
        output = args.path + output
        if os.path.exists(output):
            os.chmod(output, 0o644)
        process_template(template, output)
        os.chmod(output, 0o444)
    return 0


def process_template(template_fname, output_fname):
    """
    Read template file at ``template_fname`` and output result to
    ``output_fname``. See the module documentation for
    information on the templating language.
    """
    print(f"Reading template file {template_fname!r} ...")

    with open(template_fname, "r") as f:
        lines = f.readlines()
    print(f"  Input: {len(lines)} lines.")
    print(f"  Parsing template ...")
    out_lines = []
    out_lines.append(f"# NOTE: Do not edit this file directly! It was generated\n")
    out_lines.append(f"# automatically from the template file {template_fname!r}\n")
    out_lines.append(f"# by running ``preprocess.py``.\n")
    for p_idx, precision in enumerate(["fp32", "fp64"]):
        my_templates = dict()
        mode = "outside"  # possible modes: 'outside', 'in_template', 'in_application'
        for idx, line in enumerate(lines):
            if line.startswith("# TEMPLATE NOTE"):
                # Skip line
                continue
            elif line.startswith("# START TEMPLATE"):
                if mode == "outside":
                    argv = line.split()
                    if len(argv) > 4:
                        raise ValueError(
                            f"Syntax error on line {idx}: Template name contains spaces?"
                        )
                    if len(argv) < 4:
                        raise ValueError(
                            f"Syntax error on line {idx}: Template name missing."
                        )
                    name = argv[3]
                    if name in my_templates:
                        raise ValueError(
                            f"Error on line {idx}: Template {name!r} defined twice!"
                        )
                    my_templates[name] = []
                    mode = "in_template"
                else:
                    raise ValueError(
                        f"Syntax error on line {idx}: START TEMPLATE when not in outer mode."
                    )
            elif line.startswith("# START APPLICATION"):
                if mode == "outside":
                    argv = line.split()
                    if len(argv) > 5:
                        raise ValueError(
                            f"Syntax error on line {idx}: Too many arguments."
                        )
                    if len(argv) < 5:
                        raise ValueError(
                            f"Syntax error on line {idx}: Template or application name missing."
                        )
                    name = argv[3]
                    app = argv[4]
                    if name not in my_templates:
                        raise ValueError(
                            f"Error on line {idx}: Unknown template name {name!r}."
                        )
                    mode = "in_application"
                else:
                    raise ValueError(
                        f"Syntax error on line {idx}: START APPLICATION when not in outer mode."
                    )
            elif line.startswith("# END TEMPLATE"):
                if mode == "in_template":
                    del name
                    mode = "outside"
                else:
                    raise ValueError(
                        f"Syntax error on line {idx}: There is no template to end here."
                    )
            elif line.startswith("# END APPLICATION"):
                if mode == "in_application":
                    app += f"_{precision}"
                    app = app.replace("__", "")  # for workunits
                    # Output lines in template
                    for x in my_templates[name]:
                        p_lines = x.replace(name, app)
                        if precision == "fp32":
                            p_lines = p_lines.replace("pk.double", "pk.float")
                            p_lines = p_lines.replace("fp64", "fp32")
                        if precision == "fp64":
                            p_lines = p_lines.replace("fp32", "fp64")
                        out_lines.append(p_lines)
                    del name
                    del app
                    mode = "outside"
                else:
                    raise ValueError(
                        f"Syntax error on line {idx}: There is no application to end here."
                    )
            elif mode == "in_template":
                my_templates[name].append(line)
            elif mode == "in_application":
                out_lines.append(line)
            else:
                if p_idx == 0:
                    out_lines.append(line)
    print(f"  Output: {len(out_lines)} lines.")
    print(f"  Writing to {output_fname!r} ...")
    with open(output_fname, "w") as f:
        f.writelines(out_lines)
    print()
    return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Preprocess PyKokkos workload and workunit scripts for 'Host', 'HIP', and 'CUDA' architectures."
    )
    parser.add_argument(
        "-p",
        "--path",
        dest="path",
        type=str,
        default="",
        help="Path to output files",
    )
    args = parser.parse_args()
    exit(main(args))
